<!doctype html>
<<html>
<head>
	<meta charset="utf-8">
	<title>jQuery Events</title>
	<link rel="stylesheet" type="text/css" href="/PHPpatterns/restaurant/CSS/test.css" />
</head>
<body>
	<h1>My Website</h1>
	
	
	<div id="container",class="container">
	<?php 
		$myvar="maciek";
		
	?>
	
		<ul>
			<li>1</li>
			<li>2</li>
			<li>3</li>
			<li>4</li>
			
			
		</ul>
		
	</div>
	<button>Day</button>
	<button id="night">Night</button>
	
	
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

	<script type="text/javascript" src="/PHPpatterns/restaurant/JS/test.js"></script>	
</body>
</html>
