<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<link rel="stylesheet" type="text/css" href="./CSS/lesson7.css" />
<title>Appending content</title>
</head>
<body>
<article>
	
	<h1>My Owesome Post</h1>
	<p>
		Lorem Ipsum...
	</p>
	<p>
		<span class=co>Lorem Ipsum special texts</span>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
	</p>
	
	<p>
		<span class=co>Lorem Ipsum special texts</span>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
	</p>
	<p>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text<span class=co>Lorem Ipsum special texts</span>
	</p>
	<p>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text<span class=co>Lorem Ipsum special texts</span>
	</p>
	<p>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text<span class=co>Lorem Ipsum special texts</span>
	</p>
	<p>
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text
		the rest part of text<span class=co>Lorem Ipsum special texts</span>
	</p>
	
</article>



		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		<script type="text/javascript" src="/PHPpatterns/restaurant/JS/lesson7.js"></script>	
</body>
</html>